#################### USER TESTS ####################

POST http://localhost:8081/user/signup
Content-Type: application/json 

{
    "username" : "tocamnze",
    "email" : "cdon@gmail.com",
    "password" : "tochi12345",
    "parkId": "635ab8dfc407faf9f73deaf3",
    "dogId": "635ab8dfc407faf9f73deaf4",
    "friends": ["635ab8dfc407faf9f73deaf5", "635ab8dfc407faf9f73deaf6"],
    "eventId": "635ab8dfc407faf9f73deaf7"
}

###

POST http://localhost:8081/user/login
Content-Type: application/json 

{
    "username" : "tochiamanze",
    "password" : "tochi12345"
}

###
GET http://localhost:8081/user/getAll
Content-Type: application/json

###
PUT http://localhost:8081/user/editUser/66e1c4e8fe69956ee6e46e7e
Content-Type: application/json 

{
    "username" : "TochiEdit",
    "email": "newemail@example.com",
    "password" : "dwwrwrdfgdfgdfg",
    "parkId": "635ab8dfc407faf9f73deaf3",
    "dogId": "635ab8dfc407faf9f73deaf4",
    "friends": ["66e0a83fd41d9d3f412f240b", "66e1c26ae57d9cbb80521935"],
    "eventId": "635ab8dfc407faf9f73deaf7"
}

###
GET  http://localhost:8081/user/66e0a83fd41d9d3f412f240b
Content-Type: application/json 

###
POST  http://localhost:8081/user/deleteAll

#################### EVENT TESTS ####################

###
POST http://localhost:8081/events/create
Content-Type: application/json

{
  "userId": "64f3a8f9de85720c4b0d6ac1", 
  "parkId": "64f2b9f7d6e6571bc19f8e5b", 
  "time": "03:30", 
  "date": "2024-09-03T00:00:00Z"
}

###
GET http://localhost:8081/events/all

###
GET http://localhost:8081/events/66e1d786a1be086b1c90d9f4

###
PUT http://localhost:8081/events/update/66e1d786a1be086b1c90d9f4
Content-Type: application/json

{
  "userId": "64f3a8f9de85720c4b0d6ac1", 
  "parkId": "64f2b9f7d6e6571bc19f8e5b", 
  "time": "04:00", 
  "date": "2024-09-04T00:00:00Z"
}

###
DELETE http://localhost:8081/events/delete/66e1d786a1be086b1c90d9f4

#################### PARK TESTS ####################

###
POST http://localhost:8081/parks/create
Content-Type: application/json

{
  "parkName": "Central Park", 
  "occupants": [], 
  "eventId": [],
  "image": ""
}

###
GET http://localhost:8081/parks/all

###
GET http://localhost:8081/parks/66e1d7c8a1be086b1c90da03

###
PUT http://localhost:8081/parks/update/66e1d7c8a1be086b1c90da03
Content-Type: application/json

{
  "parkName": "Updated Park Name", 
  "occupants": ["64f3a8f9de85720c4b0d6ac1"], 
  "eventId": ["64f2b9f7d6e6571bc19f8e5b"],
  "image": "https://example.com/new-image.jpg"
}

###
DELETE http://localhost:8081/parks/delete/66e1d7c8a1be086b1c90da03

#################### DOG TESTS ####################

###
POST http://localhost:8081/dogs/create
Content-Type: application/json

{
  "dogName": "Buddy",
  "size": "medium",
  "image": "buddy-image.jpg"
}

###
GET http://localhost:8081/dogs/all

###
GET http://localhost:8081/dogs/66e1d7e4a1be086b1c90da0a

###
PUT http://localhost:8081/dogs/update/66e1d7e4a1be086b1c90da0a
Content-Type: application/json

{
  "dogName": "Max",
  "size": "large",
  "image": ""
}

###
DELETE http://localhost:8081/dogs/delete/66e1d7e4a1be086b1c90da0a
