POST http://localhost:8081/user/signup
Content-Type: application/json 

{
    "username" : "tochiamanze",
    "email" : "cdon@gmail.com",
    "password" : "tochi12345"
}

###

POST http://localhost:8081/user/login
Content-Type: application/json 

{
    "username" : "tochiamanze",
    "password" : "tochi12345"
}

###
GET http://localhost:8081/user/getAll
Content-Type: application/json

###

POST http://localhost:8081/user/editUser
Content-Type: application/json 

{
    "userId" : "635ab8dfc407faf9f73deaf2",
    "username" : "Tochi Edit",
    "password" : "dwwrwr"
}

###
GET  http://localhost:8081/user/getUserById
Content-Type: application/json 

{
    "userId" : "635ab8dfc407faf9f73deaf1"
}

###
GET  http://localhost:8081/user/getUserById
Content-Type: application/json 

{
    "userId" : "634edb2a16710b2cda6fb370"
}

###
POST  http://localhost:8081/user/deleteAll

#################### EVENT TESTS ####################

###
POST http://localhost:8081/events/create
Content-Type: application/json

{
  "userId": "64f3a8f9de85720c4b0d6ac1", 
  "parkId": "64f2b9f7d6e6571bc19f8e5b", 
  "time": "03:30", 
  "date": "2024-09-03T00:00:00Z"
}

###
GET http://localhost:8081/events/all

###
GET http://localhost:8081/events/{{eventId}}

###
PUT http://localhost:8081/events/update/66d886ff2dbb9f060b22d550
Content-Type: application/json

{
  "userId": "64f3a8f9de85720c4b0d6ac1", 
  "parkId": "64f2b9f7d6e6571bc19f8e5b", 
  "time": "04:00", 
  "date": "2024-09-04T00:00:00Z"
}

###
DELETE http://localhost:8081/events/delete/{{eventId}}

#################### PARK TESTS ####################
